services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Auto-register services in App layer
  Onion\App\Services\:
    resource: '../src/App/Services/*'
    
  # CQRS Query Handlers
  Onion\App\QueryHandlers\:
    resource: '../src/App/QueryHandlers/*'
    
  # Make services public for testing
  Onion\App\Services\BookService:
    public: true

  # Presentation layer services
  Onion\Presentation\Actions\:
    resource: '../src/Presentation/Actions/*'
    public: true

  Onion\Presentation\Adapters\:
    resource: '../src/Presentation/Adapters/*'
    public: true

  Onion\Presentation\Ports\BookManagementPort:
    alias: Onion\Presentation\Adapters\HttpBookManagementAdapter
    public: true

  Onion\Infrastructure\Services\:
    resource: '../src/Infrastructure/Services/*'

  Onion\Infrastructure\Repositories\:
    resource: '../src/Infrastructure/Repositories/*'
    exclude:
      - '../src/Infrastructure/Repositories/AbstractRepository.php'

  Onion\Infrastructure\Factory\Repositories\:
    resource: '../src/Infrastructure/Factory/Repositories/*'

  # Repository interfaces are auto-registered via RepositoryCompilerPass
  # Convention: Domain\Repositories\{Entity}RepositoryInterface -> Infrastructure\Repositories\{Entity}Repository

  Onion\Domain\Services\TransactionManagerInterface:
    alias: Onion\Infrastructure\Services\TransactionManager
    public: true

  # Database configuration (you'll want to use environment variables)
  Onion\Infrastructure\Config\DatabaseCredentials:
    arguments:
      $host: 'localhost'
      $port: 5432
      $user: 'postgres'
      $password: "@@Ucvlqcq8$"
      $database: 'onion'

  Onion\Infrastructure\Factory\PDOFactory:
    arguments:
      - '@Onion\Infrastructure\Config\DatabaseCredentials'

  PDO:
    class: PDO
    factory: ['@Onion\Infrastructure\Factory\PDOFactory', 'create']
